import type { ManagementDashboardData } from "@/types/management";

export const mockManagementData: ManagementDashboardData = {
  company: {
    name: "Adani Enterprises",
    ticker: "ADANIENT",
    exchange: "NSE",
    industry: "Infrastructure Conglomerate",
    callDate: "2024-12-17",
    confidenceLevel: "HIGH",
  },
  scores: [
    {
      factor: "Guidance Accuracy",
      rating: "HIGH",
      descriptor: "Consistent Delivery",
    },
    {
      factor: "Disclosure Honesty",
      rating: "HIGH",
      descriptor: "Transparent Ops",
    },
    {
      factor: "Capital Allocation",
      rating: "MODERATE",
      descriptor: "Value Accretive",
    },
  ],
  trust: {
    overall: "HIGH",
    subfactors: {
      governanceAccuracy: 85,
      disclosureHonesty: 92,
      capitalAllocation: 78,
    },
  },
  governanceSignals: [
    {
      id: "1",
      text: "Bad news disclosed early and explicitly",
      isPositive: true,
    },
    {
      id: "2",
      text: "Capex communicated 2 years in advance",
      isPositive: true,
    },
    {
      id: "3",
      text: "No pledging or recent stake sales",
      isPositive: true,
    },
    {
      id: "4",
      text: "Margin compression explained transparently",
      isPositive: true,
    },
  ],
  consistency: {
    score: 3.5,
    maxScore: 4.0,
    hitRate: 78,
    disclosurePattern: "Early & Explicit",
  },
  guidanceRecords: [
    {
      id: "1",
      period: "FY25",
      metric: "Revenue",
      guided: "₹4,200 Cr",
      actual: "₹4,050 Cr",
      variance: "-3.6%",
      status: "MET",
    },
    {
      id: "2",
      period: "FY25",
      metric: "EBITDA Margin",
      guided: "13-14%",
      actual: "12.8%",
      variance: "-1.5%",
      status: "MET",
    },
    {
      id: "3",
      period: "FY25",
      metric: "Capex",
      guided: "₹800 Cr",
      actual: "₹920 Cr",
      variance: "+15.0%",
      status: "MISS",
    },
    {
      id: "4",
      period: "FY24",
      metric: "Revenue",
      guided: "₹3,200 Cr",
      actual: "₹3,680 Cr",
      variance: "+15.0%",
      status: "MET",
    },
    {
      id: "5",
      period: "FY24",
      metric: "Order Book",
      guided: "₹5,000 Cr",
      actual: "₹5,500 Cr",
      variance: "+10.0%",
      status: "MET",
    },
    {
      id: "6",
      period: "FY24",
      metric: "ROCE",
      guided: "15%+",
      actual: "14.8%",
      variance: "-1.3%",
      status: "MET",
    },
    {
      id: "7",
      period: "FY24",
      metric: "Net Debt/EBITDA",
      guided: "<0.5x",
      actual: "0.42x",
      variance: "0.0%",
      status: "MET",
    },
    {
      id: "8",
      period: "FY23",
      metric: "EV Revenue",
      guided: "₹50 Cr",
      actual: "₹38 Cr",
      variance: "-24.0%",
      status: "MISS",
    },
  ],
  notablePatterns: [
    {
      id: "1",
      title: "Management consistently under-promises and over-delivers on top-line",
      description: "",
      category: "positive",
    },
    {
      id: "2",
      title: "Capex guidance tends to be underestimated by 10-20%",
      description: "",
      category: "neutral",
    },
    {
      id: "3",
      title: "Early disclosure of margin compression due to operating deleverage",
      description: "",
      category: "positive",
    },
    {
      id: "4",
      title: "Proactive communication of supply chain constraints",
      description: "",
      category: "positive",
    },
  ],
  selectedTimeframe: "rolling_3_year",
};
