import type { SampleBasket } from "../_lib/types";

/** Preview dummy baskets — replace with API later. */
export const SAMPLE_BASKETS: SampleBasket[] = [
  // Composite
  { name: "QC Composite Leaders", category: "Composite", rationale: "Highest overall QC Score — the blended Management/Opportunity/Deal composite — across the full universe.", risk: "Medium", stocks: 8, minInv: 58200, returnLabel: "1Y Return", returnVal: 16.8, volatility: "Medium", health: "Improving", fee: "₹12,000/yr" },
  { name: "Management Outperformers", category: "Composite", rationale: "Highest MOD Management-lens scores — capital allocation discipline and leadership quality.", risk: "High", stocks: 7, minInv: 38400, returnLabel: "1Y Return", returnVal: 14.2, volatility: "Medium", health: "Improving", fee: "₹12,000/yr" },
  { name: "High Opportunity Compounders", category: "Composite", rationale: "Stocks scoring highest on the MOD Opportunity lens — large addressable market, early-cycle growth.", risk: "High", stocks: 8, minInv: 52100, returnLabel: "7M Return", returnVal: 9.1, volatility: "High", health: "Improving", fee: "₹12,000/yr" },
  { name: "Best Deal Value Picks", category: "Composite", rationale: "Highest MOD Deal-lens scores — quality businesses trading at a discount to intrinsic value.", risk: "Medium", stocks: 6, minInv: 29800, returnLabel: "1Y Return", returnVal: 6.4, volatility: "Low", health: "Stable", fee: "₹12,000/yr" },

  // Lens
  { name: "Guidance Credibility Leaders", category: "Lens", rationale: "Management teams whose past guidance has most reliably matched delivered results.", risk: "Medium", stocks: 6, minInv: 41200, returnLabel: "1Y Return", returnVal: 11.3, volatility: "Low", health: "Stable", fee: "₹10,000/yr" },
  { name: "Disclosure Honesty Leaders", category: "Lens", rationale: "Highest scores on disclosure quality — consistent, complete, low-restatement reporting.", risk: "Low", stocks: 7, minInv: 47800, returnLabel: "1Y Return", returnVal: 9.7, volatility: "Low", health: "Stable", fee: "₹10,000/yr" },
  { name: "Capital Allocation Discipline", category: "Lens", rationale: "Best track record on capital deployment — reinvestment, buybacks, dividends, M&A discipline.", risk: "Medium", stocks: 8, minInv: 53600, returnLabel: "1Y Return", returnVal: 13.5, volatility: "Medium", health: "Improving", fee: "₹10,000/yr" },
  { name: "Promoter Activity Watch", category: "Lens", rationale: "Highest scores on promoter behaviour — stake changes, pledging trend, insider activity.", risk: "High", stocks: 6, minInv: 33900, returnLabel: "3M Return", returnVal: 5.2, volatility: "High", health: "Improving", fee: "₹10,000/yr" },
  { name: "Industry Tailwind Leaders", category: "Lens", rationale: "Companies whose industry backdrop scores highest — demand cycle, regulatory tailwind, structural growth.", risk: "High", stocks: 7, minInv: 44700, returnLabel: "7M Return", returnVal: 10.4, volatility: "High", health: "Improving", fee: "₹10,000/yr" },
  { name: "Competitive Moat Leaders", category: "Lens", rationale: "Strongest relative competitive position within their industry — pricing power, market share trend.", risk: "Medium", stocks: 6, minInv: 39500, returnLabel: "1Y Return", returnVal: 12.1, volatility: "Medium", health: "Stable", fee: "₹10,000/yr" },
  { name: "Financial Strength Leaders", category: "Lens", rationale: "Cleanest balance sheets in the universe — leverage, interest cover, working-capital discipline.", risk: "Low", stocks: 9, minInv: 61300, returnLabel: "1Y Return", returnVal: 10.9, volatility: "Low", health: "Stable", fee: "₹10,000/yr" },
  { name: "Customer & Distribution Leaders", category: "Lens", rationale: "Strongest customer concentration and distribution-reach profile in their category.", risk: "Medium", stocks: 6, minInv: 36800, returnLabel: "3M Return", returnVal: 6.8, volatility: "Medium", health: "Improving", fee: "₹10,000/yr" },
  { name: "Earnings Forecast Leaders", category: "Lens", rationale: "Highest-conviction forward earnings growth trajectory among covered names.", risk: "High", stocks: 8, minInv: 49200, returnLabel: "7M Return", returnVal: 14.7, volatility: "High", health: "Improving", fee: "₹10,000/yr" },
  { name: "Earnings Quality Leaders", category: "Lens", rationale: "Cleanest earnings — low accruals, high cash conversion, minimal one-offs propping up the number.", risk: "Low", stocks: 8, minInv: 57100, returnLabel: "1Y Return", returnVal: 11.6, volatility: "Low", health: "Stable", fee: "₹10,000/yr" },

  // Custom (QuantCase Special)
  { name: "Capex Cycle Beneficiaries", category: "Custom", rationale: "Companies flagged by transcript and policy-signal extraction as direct beneficiaries of rising government capex.", risk: "High", stocks: 5, minInv: 41200, returnLabel: "3M Return", returnVal: 11.8, volatility: "High", health: "Improving", fee: "₹12,000/yr" },
  { name: "Defence Momentum", category: "Custom", rationale: "Concall-extracted theme — cleared the materiality threshold on distinct-company transcript mentions this quarter.", risk: "High", stocks: 6, minInv: 63400, returnLabel: "1Y Return", returnVal: 22.9, volatility: "High", health: "Improving", fee: "₹12,000/yr" },
  { name: "PSU Navratna Compounders", category: "Custom", rationale: "Concall-extracted theme — Navratna/Miniratna classification, ranked by QC Score within the PSU universe.", risk: "High", stocks: 5, minInv: 28600, returnLabel: "1Y Return", returnVal: 17.3, volatility: "High", health: "Stable", fee: "₹12,000/yr" },
  { name: "EV & Mobility Value Chain", category: "Custom", rationale: "Concall-extracted theme — OEMs and component suppliers flagged by rising transcript mentions, ahead of any published index recognising the trend.", risk: "High", stocks: 7, minInv: 35900, returnLabel: "7M Return", returnVal: 8.6, volatility: "High", health: "Improving", fee: "₹12,000/yr" },
  { name: "Space Economy Proxies", category: "Custom", rationale: "External research idea (Jefferies, 8 Sep 2026) — no pure-play listed space company exists yet; shown here via adjacent defence/space-component suppliers.", risk: "High", stocks: 5, minInv: 44700, returnLabel: "3M Return", returnVal: 4.2, volatility: "High", health: "Improving", fee: "₹12,000/yr", history: [{ at: "2026-09-08", avgQc: 61, symbols: ["PARAS", "MTARTECH", "CGPOWER", "KAYNES", "AZAD"] }] },
  { name: "Semiconductor Ecosystem", category: "Custom", rationale: "External research idea (Jefferies, 8 Sep 2026) — OSAT/packaging plays benefiting from India's semiconductor investment cycle.", risk: "High", stocks: 2, minInv: 38900, returnLabel: "3M Return", returnVal: 9.7, volatility: "High", health: "Improving", fee: "₹12,000/yr", history: [{ at: "2026-09-08", avgQc: 68, symbols: ["KAYNES", "CGPOWER"] }] },
  { name: "Data Centre Capex Chain", category: "Custom", rationale: "External research idea (Jefferies, 8 Sep 2026) — power/electrical, cabling, cooling and backup-power suppliers to India's data-centre build-out.", risk: "High", stocks: 11, minInv: 52300, returnLabel: "3M Return", returnVal: 14.3, volatility: "Medium", health: "Improving", fee: "₹12,000/yr", history: [{ at: "2026-09-08", avgQc: 72, symbols: ["BHARTIARTL", "POWERINDIA", "CUMMINSIND", "LODHA", "POLYCAB", "ENRIN", "KEI", "VOLTAS", "KIRLOSENG", "FINCABLES", "ABB"] }] },
  { name: "Electronics Value Addition", category: "Custom", rationale: "External research idea (Jefferies, 8 Sep 2026) — component and assembly names positioned for rising domestic value addition under ECMS.", risk: "Medium", stocks: 4, minInv: 33600, returnLabel: "3M Return", returnVal: 2.8, volatility: "Medium", health: "Stable", fee: "₹12,000/yr", history: [{ at: "2026-09-08", avgQc: 64, symbols: ["KAYNES", "MOTHERSON", "DIXON", "SYRMA"] }] },
  { name: "Solar Manufacturing Chain", category: "Custom", rationale: "External research idea (Jefferies, 8 Sep 2026) — cell/module manufacturers positioned for rising domestic solar localisation.", risk: "High", stocks: 3, minInv: 29400, returnLabel: "3M Return", returnVal: -1.6, volatility: "High", health: "Weakening", fee: "₹12,000/yr", history: [{ at: "2026-09-08", avgQc: 58, symbols: ["PREMIERENE", "EMMVEE", "WAAREEENER"] }] },
  { name: "Aerospace Supply Chain", category: "Custom", rationale: "External research idea (Jefferies, 8 Sep 2026) — forging, structural and precision-component suppliers to global OEM backlogs.", risk: "High", stocks: 6, minInv: 47800, returnLabel: "3M Return", returnVal: 11.2, volatility: "High", health: "Improving", fee: "₹12,000/yr", history: [{ at: "2026-09-08", avgQc: 70, symbols: ["BHARATFORG", "MOTHERSON", "BELRISE", "AZAD", "SANSERA", "RAYMOND"] }] },

  // Thematic
  { name: "Defence Sector", category: "Thematic", rationale: "Tracks NSE's Nifty India Defence index methodology and constituents.", risk: "High", stocks: 10, minInv: 71200, returnLabel: "1Y Return", returnVal: 19.4, volatility: "High", health: "Improving", fee: "₹8,000/yr" },
  { name: "EV & New Age Automotive", category: "Thematic", rationale: "Tracks NSE's Nifty EV & New Age Automotive index — OEMs, component makers and battery/charging infrastructure names.", risk: "High", stocks: 10, minInv: 58300, returnLabel: "1Y Return", returnVal: 11.7, volatility: "High", health: "Stable", fee: "₹8,000/yr" },
  { name: "PSE / CPSE", category: "Thematic", rationale: "Tracks NSE's Nifty PSE / CPSE index — listed central public sector enterprises.", risk: "Medium", stocks: 10, minInv: 44900, returnLabel: "1Y Return", returnVal: 16.2, volatility: "Medium", health: "Stable", fee: "₹8,000/yr" },
  { name: "REITs & InvITs", category: "Thematic", rationale: "Tracks NSE's Nifty REITs & InvITs index — listed real estate and infrastructure investment trusts.", risk: "Low", stocks: 8, minInv: 39700, returnLabel: "1Y Return", returnVal: 7.8, volatility: "Low", health: "Stable", fee: "₹8,000/yr" },
  { name: "India Defence Theme", category: "Thematic", rationale: "Top QC Score names within NSE's Nifty India Defence thematic universe.", risk: "High", stocks: 4, minInv: 62100, returnLabel: "7M Return", returnVal: 4.1, volatility: "Medium", health: "Weakening", fee: "₹6,000/yr", history: [{ at: "2026-09-14", avgQc: 61, symbols: ["BEL", "HAL", "SOLARINDS", "BHARATFORG"] }] },
  { name: "India Digital Theme", category: "Thematic", rationale: "Top QC Score names within NSE's Nifty India Digital thematic universe.", risk: "High", stocks: 8, minInv: 74000, returnLabel: "1M Return", returnVal: 15.6, volatility: "High", health: "Stable", fee: "₹5,000/yr", history: [{ at: "2026-09-14", avgQc: 51, symbols: ["BHARTIARTL", "TCS", "INFY", "HCLTECH", "ETERNAL", "WIPRO", "IDEA", "TECHM"] }] },
  { name: "India Manufacturing Theme", category: "Thematic", rationale: "Top QC Score names within NSE's Nifty India Manufacturing thematic universe.", risk: "Medium", stocks: 8, minInv: 29200, returnLabel: "7M Return", returnVal: 20.6, volatility: "Medium", health: "Stable", fee: "₹9,000/yr", history: [{ at: "2026-09-14", avgQc: 50, symbols: ["RELIANCE", "SUNPHARMA", "MARUTI", "M&M", "BEL", "JSWSTEEL", "HAL", "BAJAJ-AUTO"] }] },
  { name: "Energy Theme", category: "Thematic", rationale: "Top QC Score names within NSE's Nifty Energy thematic universe.", risk: "Medium", stocks: 8, minInv: 15800, returnLabel: "1M Return", returnVal: -3.3, volatility: "Medium", health: "Improving", fee: "₹11,000/yr", history: [{ at: "2026-09-14", avgQc: 55, symbols: ["RELIANCE", "ADANIPOWER", "NTPC", "ONGC", "COALINDIA", "POWERGRID", "ADANIGREEN", "IOC"] }] },

  // Sectoral
  { name: "Banking Outperformer", category: "Sectoral", rationale: "Financial Services currently ranks #1 vs Nifty on our weekly sector scan.", risk: "High", stocks: 6, minInv: 33500, returnLabel: "3M Return", returnVal: 7.3, volatility: "Medium", health: "Improving", fee: "₹8,500/yr" },
  { name: "IT Sector Leaders", category: "Sectoral", rationale: "Information Technology relative strength turned positive vs Nifty this month.", risk: "Medium", stocks: 5, minInv: 47600, returnLabel: "3M Return", returnVal: -1.2, volatility: "Medium", health: "Weakening", fee: "₹8,500/yr" },
  { name: "Pharma Momentum", category: "Sectoral", rationale: "Healthcare sector outperformance strengthening for the third straight week.", risk: "High", stocks: 5, minInv: 36900, returnLabel: "3M Return", returnVal: 5.9, volatility: "High", health: "Improving", fee: "₹8,500/yr" },
  { name: "Auto Basket", category: "Sectoral", rationale: "Top QC Score names within NSE's Nifty Auto universe, ranked by market cap.", risk: "High", stocks: 3, minInv: 45500, returnLabel: "3M Return", returnVal: 27.9, volatility: "High", health: "Weakening", fee: "₹5,000/yr", history: [{ at: "2026-09-14", avgQc: 60, symbols: ["MARUTI", "M&M", "BAJAJ-AUTO"] }] },
  { name: "Bank Basket", category: "Sectoral", rationale: "Top QC Score names within NSE's Nifty Bank universe, ranked by market cap.", risk: "High", stocks: 3, minInv: 51100, returnLabel: "3M Return", returnVal: -1.7, volatility: "Medium", health: "Stable", fee: "₹7,000/yr", history: [{ at: "2026-09-14", avgQc: 77, symbols: ["HDFCBANK", "ICICIBANK", "SBIN"] }] },
  { name: "IT Basket", category: "Sectoral", rationale: "Top QC Score names within NSE's Nifty IT universe, ranked by market cap.", risk: "Medium", stocks: 3, minInv: 31300, returnLabel: "1M Return", returnVal: 13.7, volatility: "High", health: "Weakening", fee: "₹10,000/yr", history: [{ at: "2026-09-14", avgQc: 60, symbols: ["TCS", "INFY", "HCLTECH"] }] },
  { name: "Healthcare Basket", category: "Sectoral", rationale: "Top QC Score names within NSE's Nifty Healthcare universe, ranked by market cap.", risk: "High", stocks: 5, minInv: 41700, returnLabel: "3M Return", returnVal: -5.7, volatility: "Medium", health: "Improving", fee: "₹11,000/yr", history: [{ at: "2026-09-14", avgQc: 83, symbols: ["SUNPHARMA", "DIVISLAB", "TORNTPHARM", "APOLLOHOSP", "CIPLA"] }] },
  { name: "FMCG Basket", category: "Sectoral", rationale: "Top QC Score names within NSE's Nifty FMCG universe, ranked by market cap.", risk: "Medium", stocks: 3, minInv: 16900, returnLabel: "1M Return", returnVal: 13.3, volatility: "Medium", health: "Improving", fee: "₹12,000/yr", history: [{ at: "2026-09-14", avgQc: 65, symbols: ["HINDUNILVR", "ITC", "NESTLEIND"] }] },
  { name: "Metal Basket", category: "Sectoral", rationale: "Top QC Score names within NSE's Nifty Metal universe, ranked by market cap.", risk: "Medium", stocks: 3, minInv: 41300, returnLabel: "1Y Return", returnVal: 18.3, volatility: "Medium", health: "Stable", fee: "₹5,000/yr", history: [{ at: "2026-09-14", avgQc: 84, symbols: ["ADANIENT", "JSWSTEEL", "TATASTEEL"] }] },
  { name: "Realty Basket", category: "Sectoral", rationale: "Top QC Score names within NSE's Nifty Realty universe, ranked by market cap.", risk: "Medium", stocks: 3, minInv: 59400, returnLabel: "7M Return", returnVal: 14.8, volatility: "Medium", health: "Improving", fee: "₹12,000/yr", history: [{ at: "2026-09-14", avgQc: 81, symbols: ["DLF", "LODHA", "PHOENIXLTD"] }] },

  // Broad Based
  { name: "Large Cap Compounder", category: "Broad Based", rationale: "Top QC Score names ranked #1-100 by real market cap — no sector constraint.", risk: "Medium", stocks: 8, minInv: 61200, returnLabel: "1Y Return", returnVal: 12.6, volatility: "Low", health: "Stable", fee: "₹6,000/yr" },
  { name: "Mid Cap Compounder", category: "Broad Based", rationale: "Top QC Score names ranked #101-250 by real market cap.", risk: "High", stocks: 8, minInv: 44300, returnLabel: "1Y Return", returnVal: 18.4, volatility: "Medium", health: "Improving", fee: "₹6,000/yr" },
  { name: "Small Cap Compounder", category: "Broad Based", rationale: "Top QC Score names ranked #251-500 by real market cap.", risk: "High", stocks: 7, minInv: 22800, returnLabel: "1Y Return", returnVal: 21.7, volatility: "High", health: "Improving", fee: "₹6,000/yr" },
  { name: "Micro Cap Explorer", category: "Broad Based", rationale: "Top QC Score names ranked #500+ by real market cap — highest-risk tier.", risk: "High", stocks: 6, minInv: 14900, returnLabel: "3M Return", returnVal: -3.4, volatility: "High", health: "Weakening", fee: "₹6,000/yr" },
  { name: "Flexicap Select", category: "Broad Based", rationale: "Best QC Score names across all cap tiers combined — no size constraint at all.", risk: "Medium", stocks: 9, minInv: 58700, returnLabel: "1Y Return", returnVal: 15.1, volatility: "Medium", health: "Stable", fee: "₹6,000/yr" },

  // Strategy
  { name: "Alpha 50", category: "Strategy", rationale: "Built on NSE's Nifty Alpha 50 factor methodology.", risk: "High", stocks: 8, minInv: 44900, returnLabel: "3M Return", returnVal: 24.5, volatility: "Medium", health: "Improving", fee: "₹7,000/yr", history: [{ at: "2026-09-14", avgQc: 47, symbols: ["ADANIPOWER", "DELHIVERY", "SBIN", "FORTIS", "TVSMOTOR", "IDEA", "ATHERENERG", "NYKAA"] }] },
  { name: "Low Volatility 50", category: "Strategy", rationale: "Built on NSE's Nifty Low Volatility 50 factor methodology.", risk: "Medium", stocks: 8, minInv: 19500, returnLabel: "3M Return", returnVal: -7.1, volatility: "High", health: "Improving", fee: "₹12,000/yr", history: [{ at: "2026-09-14", avgQc: 58, symbols: ["DMART", "RELIANCE", "HDFCBANK", "BHARTIARTL", "LT", "JSWSTEEL", "BAJAJFINSV", "ICICIBANK"] }] },
  { name: "Quality 30 (Nifty100)", category: "Strategy", rationale: "Built on NSE's Nifty100 Quality 30 factor methodology.", risk: "High", stocks: 7, minInv: 61600, returnLabel: "3M Return", returnVal: 4.5, volatility: "Medium", health: "Improving", fee: "₹8,000/yr", history: [{ at: "2026-09-14", avgQc: 54, symbols: ["HAL", "VBL", "HINDZINC", "BOSCHLTD", "LTM", "HINDUNILVR", "BEL"] }] },
  { name: "Value 30 (Nifty200)", category: "Strategy", rationale: "Built on NSE's Nifty200 Value 30 factor methodology.", risk: "High", stocks: 7, minInv: 61400, returnLabel: "1Y Return", returnVal: 13.5, volatility: "Medium", health: "Weakening", fee: "₹6,000/yr", history: [{ at: "2026-09-14", avgQc: 83, symbols: ["SBIN", "PNB", "IOC", "UPL", "ONGC", "INDUSINDBK", "BPCL"] }] },
  { name: "Momentum 50 (Nifty500)", category: "Strategy", rationale: "Built on NSE's Nifty500 Momentum 50 factor methodology.", risk: "Medium", stocks: 8, minInv: 74200, returnLabel: "7M Return", returnVal: 27.2, volatility: "High", health: "Stable", fee: "₹5,000/yr", history: [{ at: "2026-09-14", avgQc: 49, symbols: ["ADANIPOWER", "KIRLOSENG", "RRKABEL", "NLCINDIA", "IDEA", "ATHERENERG", "ADANIENSOL", "THERMAX"] }] },
  { name: "Dividend Opportunities 50", category: "Strategy", rationale: "Built on NSE's Nifty Dividend Opportunities 50 factor methodology.", risk: "High", stocks: 8, minInv: 70700, returnLabel: "1M Return", returnVal: 20.6, volatility: "Medium", health: "Stable", fee: "₹5,000/yr", history: [{ at: "2026-09-14", avgQc: 89, symbols: ["NHPC", "IRFC", "HINDZINC", "SBIN", "PNB", "IOC", "ONGC", "BPCL"] }] },
  { name: "High Beta 50", category: "Strategy", rationale: "Built on NSE's Nifty High Beta 50 factor methodology.", risk: "High", stocks: 8, minInv: 25400, returnLabel: "1Y Return", returnVal: 20.9, volatility: "Medium", health: "Improving", fee: "₹5,000/yr", history: [{ at: "2026-09-14", avgQc: 62, symbols: ["ADANIPORTS", "ADANIENT", "DLF", "CHOLAFIN", "PRESTIGE", "INDIGO", "GODREJPROP", "RVNL"] }] },
  { name: "Equal Weight (Nifty100)", category: "Strategy", rationale: "Built on NSE's Nifty100 Equal Weight factor methodology.", risk: "Medium", stocks: 8, minInv: 59500, returnLabel: "1M Return", returnVal: 10.9, volatility: "High", health: "Improving", fee: "₹6,000/yr", history: [{ at: "2026-09-14", avgQc: 80, symbols: ["HYUNDAI", "DMART", "TATACAP", "TMCV", "BAJFINANCE", "ENRIN", "RELIANCE", "BAJAJHLDNG"] }] },

  // Technical
  { name: "Trend Leaders (Above 200 SMA)", category: "Technical", rationale: "Stocks holding firmly above their 200-day moving average, confirmed by ADX trend strength.", risk: "Medium", stocks: 8, minInv: 31600, returnLabel: "1M Return", returnVal: 3.8, volatility: "Medium", health: "Improving", fee: "₹5,000/yr" },
  { name: "Oversold Bounce Candidates", category: "Technical", rationale: "RSI oversold with early reversal confirmation near a support zone.", risk: "High", stocks: 6, minInv: 19200, returnLabel: "1M Return", returnVal: -2.1, volatility: "High", health: "Weakening", fee: "₹5,000/yr" },
  { name: "Sector RS Breakouts", category: "Technical", rationale: "Stocks outperforming both their own sector and Nifty on relative strength, across sectors.", risk: "High", stocks: 7, minInv: 27900, returnLabel: "1M Return", returnVal: 6.7, volatility: "High", health: "Improving", fee: "₹5,000/yr" },
];
